(()=>{"use strict";
const SEED=[
{id:"mr-wash-park",name:"Maple Ridge Park — Public Washrooms",category:"washroom",lat:49.2456,lng:-122.5716,address:"13180 232 St / 23280 132 Ave, Maple Ridge, BC",gender:"All-gender / accessible facilities",access:"Public park facility",fee:"Free",hours:"Park/facility hours vary",detail:"Public washroom facilities; accessibility information should be checked on site.",source:"City of Maple Ridge",url:"https://www.mapleridge.ca/art-parks-rec/recreation-facilities/maple-ridge-park"},
{id:"mr-wash-kanaka",name:"Kanaka Creek Regional Park — Washrooms",category:"washroom",lat:49.2188,lng:-122.5369,address:"23150 River Rd, Maple Ridge, BC",gender:"All-gender / accessible facilities",access:"Public park facility",fee:"Free",hours:"Park hours / seasonal availability",detail:"Accessible washrooms are listed among park amenities.",source:"Metro Vancouver",url:"https://metrovancouver.org/services/kanaka-creek-regional-park"},
{id:"mr-wash-albion",name:"Albion Sports Complex — Washrooms",category:"washroom",lat:49.1925,lng:-122.5520,address:"23778 104 Ave, Maple Ridge, BC",gender:"Public / accessible facility",access:"Public recreation facility",fee:"Free during facility access",hours:"Facility hours vary",detail:"Washroom facilities associated with the sports complex.",source:"City of Maple Ridge",url:"https://www.mapleridge.ca/parks-recreation-culture/recreation-facilities"},
{id:"mr-water-park",name:"Maple Ridge Park — Drinking Water",category:"water",lat:49.2456,lng:-122.5716,address:"13180 232 St / 23280 132 Ave, Maple Ridge, BC",water:"Drinking water / refill",access:"Public park facility",fee:"Free",hours:"Seasonal / facility hours",detail:"Drinking-water amenity listed for the park.",source:"City of Maple Ridge",url:"https://www.mapleridge.ca/art-parks-rec/recreation-facilities/maple-ridge-park"},
{id:"mr-water-kanaka",name:"Kanaka Creek Regional Park — Water",category:"water",lat:49.2188,lng:-122.5369,address:"23150 River Rd, Maple Ridge, BC",water:"Drinking water",access:"Public park facility",fee:"Free",hours:"Seasonal / facility hours",detail:"Water service is listed among park amenities.",source:"Metro Vancouver",url:"https://metrovancouver.org/services/kanaka-creek-regional-park"},
{id:"mr-park-park",name:"Maple Ridge Park — Parking",category:"parking",lat:49.2456,lng:-122.5716,address:"13180 232 St / 23280 132 Ave, Maple Ridge, BC",parking:"Park parking",fee:"Free / conditions may vary",hours:"Park hours",detail:"Parking available for park visitors; restrictions and event conditions may apply.",source:"City of Maple Ridge",url:"https://www.mapleridge.ca/art-parks-rec/recreation-facilities/maple-ridge-park"},
{id:"mr-park-kanaka",name:"Kanaka Creek Regional Park — Parking",category:"parking",lat:49.2188,lng:-122.5369,address:"23150 River Rd, Maple Ridge, BC",parking:"Park parking",fee:"Free / conditions may vary",hours:"Park hours",detail:"Parking is listed among park amenities.",source:"Metro Vancouver",url:"https://metrovancouver.org/services/kanaka-creek-regional-park"},
{id:"mr-park-albion",name:"Albion Sports Complex — Parking",category:"parking",lat:49.1925,lng:-122.5520,address:"23778 104 Ave, Maple Ridge, BC",parking:"Large parking area",fee:"Free / facility conditions may vary",hours:"Facility hours vary",detail:"Parking associated with the sports complex.",source:"City of Maple Ridge",url:"https://www.mapleridge.ca/parks-recreation-culture/recreation-facilities"},
{id:"mr-ev-haney",name:"BC Hydro EV Charging — Haney Place",category:"ev",lat:49.2191,lng:-122.6017,address:"Haney Place area, Maple Ridge, BC",charger:"Public EV charging",fee:"Pricing varies by network/session",hours:"24/7 site access may vary",detail:"Public charging listing; connector type, power and live availability can change.",source:"Public charging directory",url:"https://chargehub.com/"},
{id:"mr-ev-dewdney",name:"EV Charging — 22470 Dewdney Trunk Rd",category:"ev",lat:49.2195,lng:-122.6042,address:"22470 Dewdney Trunk Rd, Maple Ridge, BC",charger:"Public Level 2 / charging listing",fee:"Pricing varies by network/session",hours:"Site access varies",detail:"Public charging listing; confirm connector, price and availability before relying on it.",source:"Public charging directory",url:"https://chargehub.com/"},
{id:"mr-gas-1",name:"Fuel Station — Downtown Maple Ridge",category:"gas",lat:49.2198,lng:-122.6025,address:"Maple Ridge, BC",fuel:"Gasoline / diesel may be available",fee:"Fuel price varies",hours:"Station hours vary",detail:"Fuel pricing and pump availability change continuously.",source:"OpenStreetMap",url:"https://www.openstreetmap.org/"}
];
const DEFAULT={lat:49.224,lng:-122.692},ICON={washroom:"🚻",water:"💧",parking:"P",ev:"⚡",gas:"⛽"},LABEL={washroom:"WASHROOM",water:"WATER",parking:"PARKING",ev:"EV CHARGING",gas:"GAS"};
let map,layer,userMarker,user=null,places=SEED.slice(),cat="all",radius=5,term="";
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const km=(a,b,c,d)=>{let R=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const center=()=>user||DEFAULT;
function iconFor(p){return L.divIcon({className:"",html:`<div class="marker marker-${p.category}">${ICON[p.category]}</div>`,iconSize:[44,44],iconAnchor:[22,22]})}
function initMap(){
 map=L.map("map",{preferCanvas:true,zoomControl:false,attributionControl:false,fadeAnimation:false,zoomAnimation:true}).setView([DEFAULT.lat,DEFAULT.lng],13);
 L.control.zoom({position:"bottomright"}).addTo(map);
 L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,keepBuffer:2,updateWhenIdle:true,attribution:"© OpenStreetMap contributors"}).addTo(map);
 layer=L.layerGroup().addTo(map);requestAnimationFrame(render);
 setTimeout(locationRequest,200);setTimeout(liveFetch,500);
}
function classify(t){if(t.amenity==="toilets")return"washroom";if(t.amenity==="drinking_water")return"water";if(t.amenity==="parking")return"parking";if(t.amenity==="charging_station")return"ev";if(t.amenity==="fuel"||t.shop==="fuel")return"gas";return null}
function normalize(e){
 let t=e.tags||{},c=classify(t),lat=e.lat??e.center?.lat,lng=e.lon??e.center?.lon;if(!c||!Number.isFinite(lat)||!Number.isFinite(lng))return null;
 let access=t.access||t.fee||t.opening_hours||"", gender=t["toilets:gender"]||t.gender||t["toilets:unisex"]==="yes"?"Unisex / all-gender":"Not specified";
 let fee=t.fee==="no"?"Free":t.fee==="yes"?"Paid / fee applies":t["charge"]||"Not specified";
 let price=t.price||t["charge:fee"]||"Not listed";
 if(c==="parking") fee=t.fee==="no"?"Free parking":t.fee==="yes"?"Paid parking":"Parking fee not specified";
 if(c==="gas") price=t["fuel:price"]||t.price||"Price not listed";
 return {id:`osm-${e.type}-${e.id}`,name:t.name||({washroom:"Public washroom",water:"Drinking water",parking:"Parking",ev:"EV charging station",gas:"Fuel station"}[c]),category:c,lat,lng,address:[t["addr:housenumber"],t["addr:street"],t["addr:city"]].filter(Boolean).join(" ")||"Address not listed",gender,access:access||"Access not specified",fee,hours:t.opening_hours||"Hours not specified",detail:c==="ev"?[t.socket,t["socket:type2"],t.capacity?`${t.capacity} kW`:""].filter(Boolean).join(" • ")||"Connector/power not specified":c==="gas"?(t.brand||"Fuel station"):(c==="parking"?(t.capacity?`${t.capacity} spaces`:"Capacity not listed"):(t.drinking_water?"Drinking water":"Facility details not specified")),source:"OpenStreetMap",url:"https://www.openstreetmap.org/"};
}
function overpassQuery(lat,lng,r){return `[out:json][timeout:10];nwr(around:${r*1000},${lat},${lng})["amenity"~"toilets|drinking_water|parking|charging_station|fuel"];nwr(around:${r*1000},${lat},${lng})["shop"="fuel"];out center tags;`}
async function liveFetch(){
 const c=center(),endpoints=["https://overpass-api.de/api/interpreter","https://overpass.private.coffee/api/interpreter"];
 for(const ep of endpoints)try{let ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),8500),r=await fetch(ep,{method:"POST",body:overpassQuery(c.lat,c.lng,radius),signal:ctl.signal,headers:{"Content-Type":"text/plain;charset=UTF-8"}});clearTimeout(tm);if(!r.ok)continue;let j=await r.json(),live=j.elements.map(normalize).filter(Boolean),all=[...SEED,...live],u=[];for(const p of all)if(!u.some(q=>p.category===q.category&&km(p.lat,p.lng,q.lat,q.lng)<.025&&(p.name===q.name||p.name.includes(q.name)||q.name.includes(p.name))))u.push(p);places=u;localStorage.setItem("pitstop-cache",JSON.stringify({places,time:Date.now()}));render();return}catch(e){}}
function filtered(){let c=center();return places.map(p=>({...p,distance:km(c.lat,c.lng,p.lat,p.lng)})).filter(p=>(cat==="all"||p.category===cat)&&p.distance<=radius&&(!term||`${p.name} ${p.address} ${p.detail} ${p.fee} ${p.hours}`.toLowerCase().includes(term))).sort((a,b)=>a.distance-b.distance)}
function render(){
 if(!map)return;let list=filtered();layer.clearLayers();list.forEach(p=>L.marker([p.lat,p.lng],{icon:iconFor(p)}).on("click",()=>modal(p)).addTo(layer));
 $("#count").textContent=list.length;$("#results").innerHTML=list.length?list.map(p=>`<button class="result" data-id="${esc(p.id)}"><span><b>${esc(p.name)}</b><em>${p.distance<.1?Math.round(p.distance*1000)+" m":p.distance.toFixed(1)+" km"}</em></span><small>${esc(p.address)}</small><i>${esc(p.fee||"Cost not specified")}</i></button>`).join(""):`<div class="result empty"><b>No matches in this radius</b><small>Expand the radius or change category.</small></div>`;
 $$(".result[data-id]").forEach(b=>b.onclick=()=>{let p=places.find(x=>x.id===b.dataset.id);if(p){map.flyTo([p.lat,p.lng],16,{duration:.4});modal(p)}})
 if(user){if(!userMarker)userMarker=L.marker([user.lat,user.lng],{icon:L.divIcon({className:"",html:"<div class=user-dot></div>",iconSize:[18,18],iconAnchor:[9,9]})}).addTo(map);else userMarker.setLatLng([user.lat,user.lng])}
}
function modal(p){
 let d=km(center().lat,center().lng,p.lat,p.lng);$("#modalCat").textContent=LABEL[p.category];$("#modalTitle").textContent=p.name;$("#modalDistance").textContent=d<.1?Math.round(d*1000)+" m away":d.toFixed(1)+" km away";$("#mAddress").textContent=p.address;$("#mAccess").textContent=p.access||"Not specified";$("#mCost").textContent=p.fee||"Not specified";$("#mHours").textContent=p.hours||"Not specified";$("#mDetail").textContent=p.detail||"Not specified";$("#mGender").textContent=p.gender||"Not applicable";$("#directions").href=`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`;$("#source").href=p.url||"https://www.openstreetmap.org/";$("#modal").classList.add("open")}
function closeModal(){$("#modal").classList.remove("open")}
function locationRequest(){if(!navigator.geolocation){$("#locationText").textContent="GPS unavailable — using Maple Ridge.";return}navigator.geolocation.getCurrentPosition(p=>{user={lat:p.coords.latitude,lng:p.coords.longitude};$("#locationText").textContent="Using your current location.";map.flyTo([user.lat,user.lng],14,{duration:.5});render();liveFetch()},()=>$("#locationText").textContent="Maple Ridge default • GPS not granted",{timeout:4500,maximumAge:300000,enableHighAccuracy:false})}
$("#search")?.addEventListener("input",e=>{term=e.target.value.toLowerCase().trim();render()});
$("#search")?.addEventListener("keydown",async e=>{if(e.key!=="Enter")return;let q=e.currentTarget.value.trim();if(!q)return;$("#locationText").textContent="Searching worldwide…";try{let r=await fetch("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q="+encodeURIComponent(q),{headers:{"Accept-Language":"en"}}),a=await r.json();if(!a.length){$("#locationText").textContent="Place not found.";return}user={lat:+a[0].lat,lng:+a[0].lon};map.flyTo([user.lat,user.lng],13,{duration:.6});$("#locationText").textContent=a[0].display_name;term="";e.currentTarget.value="";render();liveFetch()}catch{$("#locationText").textContent="Place search temporarily unavailable."}});
$$(".chip").forEach(b=>b.onclick=()=>{$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");cat=b.dataset.cat;render()});
$$(".radius button").forEach(b=>b.onclick=()=>{$$(".radius button").forEach(x=>x.classList.remove("active"));b.classList.add("active");radius=+b.dataset.radius;render();liveFetch()});
$("#locateBtn")?.addEventListener("click",locationRequest);$("#recenter")?.addEventListener("click",()=>{let c=center();map.flyTo([c.lat,c.lng],user?14:13,{duration:.4})});$("#modalClose")?.addEventListener("click",closeModal);$("#modal")?.addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});document.addEventListener("keydown",e=>e.key==="Escape"&&closeModal());
$("#menuBtn")?.addEventListener("click",()=>$("#mobileNav")?.classList.toggle("open"));
$("#themeBtn")?.addEventListener("click",()=>{let light=document.body.classList.toggle("light");localStorage.setItem("pitstop-theme",light?"light":"dark");$("#themeBtn").textContent=light?"☾":"☀"});
if(localStorage.getItem("pitstop-theme")==="light"){document.body.classList.add("light");if($("#themeBtn"))$("#themeBtn").textContent="☾"}
/* lightweight global 3D scroll/parallax */
let ticking=false;function fx(){let y=scrollY;document.documentElement.style.setProperty("--sy",y+"px");$$(".depth").forEach(el=>{let r=el.getBoundingClientRect(),d=(r.top+r.height/2-innerHeight/2)/innerHeight;el.style.transform=`translate3d(0,${-d*12}px,0) rotateX(${d*1.2}deg)`});let g=$("#heroGrid");if(g)g.style.transform=`perspective(700px) rotateX(${64-Math.min(y*.01,10)}deg) rotateZ(${-8+Math.min(y*.003,4)}deg) translate3d(0,${Math.min(y*.25,160)}px,0) scale(${1.25+y*.00015})`;ticking=false}addEventListener("scroll",()=>{if(!ticking){ticking=true;requestAnimationFrame(fx)}},{passive:true});
$$(".tilt").forEach(c=>{c.onpointermove=e=>{if(innerWidth<760)return;let r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(800px) rotateX(${-y*7}deg) rotateY(${x*7}deg) translateZ(10px)`};c.onpointerleave=()=>c.style.transform=""});
$$(".faq-q").forEach(q=>q.onclick=()=>q.parentElement.classList.toggle("open"));
$("#contactForm")?.addEventListener("submit",e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.currentTarget)),a=JSON.parse(localStorage.getItem("pitstop-suggestions")||"[]");a.push({...d,time:new Date().toISOString()});localStorage.setItem("pitstop-suggestions",JSON.stringify(a));$("#formNotice").textContent="Saved on this device. You can copy the suggestion below.";$("#copySuggestion").hidden=false;$("#copySuggestion").onclick=()=>navigator.clipboard?.writeText(JSON.stringify(d,null,2)).then(()=>$("#formNotice").textContent="Copied.")});
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
document.addEventListener("DOMContentLoaded",()=>{if($("#map"))initMap();else fx()});
})();